export const HOME_FETCHING = 'HOME_FETCHING';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAILED = 'HOME_FAILED';
export const HOME_RESET = 'HOME_RESET';

export const FOOTER_UPDATE_COUNT = 'FOOTER_UPDATE_COUNT';