export const AS_ACCOUNT = 'AS_ACCOUNT'
export const AS_AUTHEN_SUCCESS = 'AS_AUTHEN_SUCCESS'

export const JSON_FETCHING = 'JSON_FETCHING';
export const JSON_SUCCESS = 'JSON_SUCCESS';
export const JSON_FAILED = 'JSON_FAILED';

export const ACTIVITY_ADD = 'ACTIVITY_ADD';
export const ACTIVITY_CLEAR = 'ACTIVITY_CLEAR';


export const JSON_REQUEST = 'JSON_REQUEST';

export const ACTIVITY_ADD_REQUEST = 'ACTIVITY_ADD_REQUEST';
export const ACTIVITY_CLEAR_REQUEST = 'ACTIVITY_CLEAR_REQUEST';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const REGISTER_REQUEST = 'AUTH_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

