
// HOME
export const HOME_LOGIN_REQ = "HOME_LOGIN_REQ";
export const HOME_LOGIN_SUCCESS = "HOME_LOGIN_SUCCESS";
export const HOME_LOGIN_FAILED = "HOME_LOGIN_FAILED";

// JSONFEED
export const JSONFEED_FETCHING_DATA = "JSONFEED_FETCHING_DATA";
export const JSONFEED_FETCHING_SUCCESS = "JSONFEED_FETCHING_SUCCESS";
export const JSONFEED_FETCHING_FAILED = "JSONFEED_FETCHING_FAILED";

